name: slap_that_bite
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  cupertino_icons: ^1.0.2
  flame: ^1.12.0
  flame_audio: ^2.1.5
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  vibration: ^1.8.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
